# Generated by Django 4.2.17 on 2025-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.CharField(
                choices=[
                    ("movie", "Фильм"),
                    ("series", "Сериал"),
                    ("cartoon", "Мультфильм"),
                ],
                default="movie",
                max_length=10,
            ),
        ),
    ]
