# Generated by Django 4.2.17 on 2025-02-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_movie_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("comedy", "Комедия"),
                    ("drama", "Драма"),
                    ("horror", "Ужасы"),
                    ("fantasy", "Фэнтези"),
                    ("action", "Боевик"),
                    ("thriller", "Триллер"),
                ],
                default="horror",
                max_length=15,
            ),
        ),
    ]
