# Generated by Django 4.2.17 on 2025-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_movie_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
