# Generated by Django 4.2.17 on 2025-01-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_activate"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cinema.typesubscription",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Activate",
        ),
    ]
