# Generated by Django 4.2.17 on 2025-01-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="cinema.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="cinema.typesubscription",
            ),
        ),
    ]
