# Generated by Django 4.2.17 on 2025-02-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.CharField(
                choices=[
                    (1, "Очень плохо"),
                    (2, "Плохо"),
                    (3, "Нейтрально"),
                    (4, "Хорошо"),
                    (5, "Отлично"),
                ],
                default="neutral",
                max_length=15,
            ),
        ),
    ]
