# Generated by Django 4.2.17 on 2025-02-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0006_alter_rating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
    ]
