# Generated by Django 4.2.17 on 2025-02-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0007_rating_avg_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="avg_rating",
        ),
    ]
