# Generated by Django 4.2.17 on 2025-02-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0008_remove_rating_avg_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="cinema.typesubscription",
            ),
        ),
    ]
