# Generated by Django 4.2.17 on 2025-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0009_alter_movie_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.URLField(
                blank=True,
                default="https://www.iphones.ru/wp-content/uploads/2015/05/errfolder.jpg",
                max_length=1500,
            ),
        ),
    ]
